### ISSUE TITLE
EVMK WL 2085

### ISSUE THREAD

**Issue by MartinRoth** [KNMI/knmitransformer#32]
Regression test does not fit web data (evmk WL 2085)
If one uses web temperature and web radiation -> fits regression test

Version v1.0 temperature is different from web data
Version v1.0 evmk is the same as web data

Version v1.0_T25 has more stations (25) (e.g. temperature)

- Check rsds
- Check files sent for the revised version
- Check output of makking(v1.0_T25 data, ...)

**Comment by cphotiadou** [comment]
- Version v1.0 (CP) rsds is the same as web data
- Janette got both versions - v1.0 & v1.0_T25
- makkink output calculated with tg v1.0_T25 data once the extra 11 stations were removed -> fits regression test
- web data (evmk WL 2085) does not fit with Jules old version (diff even bigger)
